MODEL:
  NUM_LAYERS: 2
  LAMBDA: [0.0]

TRAIN:
  DATASET: 'CIFAR10' #CIFAR10 or MNIST
  LR: 0.0005
  LR_SCHE_FACTOR: 0.1
  LR_SCHE_STEP: [5000]
  OPTIMIZER: 'Adam' 
  ADAM_BETA1: 0.0
  ADAM_BETA2: 0.9
  EPOCHS: 5000
  BATCH_SIZE: 2000
  ARCH: 'INVERSE2'
  NZ: 512
  NGF: 64
  MODE: 'binary'