MODEL:
  NUM_LAYERS: 2
  LAMBDA: [0.0]

TRAIN:
  DATASET: 'CIFAR10' #CIFAR10 or MNIST
  LR: 0.0002
  LR_SCHE_FACTOR: 0.1
  LR_SCHE_STEP: [None]
  OPTIMIZER: 'Adam' 
  ADAM_BETA1: 0.0
  ADAM_BETA2: 0.9
  EPOCHS: 2000
  BATCH_SIZE: 4000
  ARCH: 'INVERSE4'
  NZ: 512
  NGF: 64
  MODE: 'multi'