MODEL:
  NUM_LAYERS : 2
  LAMBDA : [0.0]

TRAIN:
  DATASET : 'MNIST' #CIFAR10 or MNIST
  LR : 0.0001
  LR_SCHE_FACTOR : 0.1
  LR_SCHE_STEP : [100, 200]
  OPTIMIZER : 'Adam' 
  ADAM_BETA1 : 0.0
  ADAM_BETA2 : 0.9
  EPOCHS : 200
  BATCH_SIZE : 2048
  ARCH : 'INVERSE2'
  NZ : 128
  NGF : 64
  MODE : 'binary'